###
POST http://localhost:3003 HTTP/1.1
Content-Type: application/json

{
    "titulo" : "Ejemplo 4",
    "descripcion" : "lorem ipsum dolor sit amet",
    "sala": "sala 5",
    "imagen": "imagen 7"
}

###
GET http://localhost:3003/ HTTP/1.1

###
GET http://localhost:3003/6275abe7cf665f7ac54638ed HTTP/1.1

###
PUT http://localhost:3003/6275abe7cf665f7ac54638ed HTTP/1.1
Content-Type: application/json

{
    "titulo" : "Ejemplo 5",
    "descripcion" : "lorem ipsum dolor sit amet",
    "sala": "sala 5",
    "imagen": "imagen 5"
}

###
DELETE http://localhost:3003/6275b4c2310f1f5f5a8b60ac HTTP/1.1

###
GET http://localhost:3003/siete HTTP/1.1